name: 'hydrocarbons_dashboard'
version: '1.0.0'
config-version: 2

profile: 'hydrocarbons_dashboard'

# This is where dbt will look for .sql files
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  hydrocarbons_dashboard:
    staging:
      +materialized: view
    marts:
      +materialized: table

# Optional: treat warnings as errors (strict mode)
# flags:
#   warn-error: true
